service: hello-world
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x

functions:
  hello:
    handler: handler.hello
    events:
       - http:
          path: wish
          method: get
plugins:
  - serverless-offline